default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL']%>
  
production:
  <<: *default
  database: next_game

test:
  <<: *default
  database: next_game_test

development:
  <<: *default
  database: next_game_development
