default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: michaelhuang
  password: <%= ENV['DB_PASSWORD'] %>
  
development:
  <<: *default
  database: next_game_development

test:
  <<: *default
  database: next_game_test

production:
  <<: *default
  database: next_game_production
  password: <%= ENV['DB_PASSWORD'] %>
